###
POST http://127.0.0.1:4000/api/wilders HTTP/1.1
content-type: application/json

{
    "name": "baba",
    "city": "Tullins",
    "skills":[
        {"title": "express", "votes":5},
        {"title": "mongo", "votes":12}
    ],
    "image": "62324987a382f6925882ca3b"
}

###
GET http://127.0.0.1:4000/api/wilders HTTP/1.1

###

GET http://127.0.0.1:4000/api/wilders/6232f3acf5166e2ab7720513 HTTP/1.1

###

DELETE http://127.0.0.1:4000/api/wilders/622783bba94be564d464bcad HTTP/1.1


###
PATCH http://127.0.0.1:4000/api/wilders/622778ceeb5c77c442ec4dfe HTTP/1.1
content-type: application/json

{
    "name": "Thomas",
    "city": "SF",
    "skills": [
        {"title": "express", "votes":5},
        {"title": "mongo", "votes":12}
    ]
}

###
POST http://127.0.0.1:4000/api/images HTTP/1.1
content-type: multipart/form-data

{
    "name": "JPG",
    "desc": "This is a image",
    "img":
    {
        "data": "012",
        "contentType": "String"
    }
}

###
GET http://127.0.0.1:4000/api/images HTTP/1.1